name: Monitoring GitOps CI

on:
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Promtool
        run: |
          wget https://github.com/prometheus/prometheus/releases/download/v3.11.3/prometheus-3.11.3.linux-amd64.tar.gz
          tar -xzf prometheus-3.11.3.linux-amd64.tar.gz
          sudo cp prometheus-3.11.3.linux-amd64/promtool /usr/local/bin/      
      
      - name: Validate Prometheus config
        run: |
          promtool check config prometheus/prometheus.yml

      - name: Validate Alertmanager config
        run: |
          echo "Skipping amtool install for now (next step upgrade)"
